# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1499c698117703344208b62d1d800db75afa515045920566b4a3a5f6b53594574c674be3e4d8d0344b7cd163fad4ec139063315eb2759d290fabbb522d63d09f

test:
  secret_key_base: 73999b844b72446bbd5ad9cf974590a23c0ec06fedcce3836339c6836a07baef4f4f9d9c0990133aeffa2155da313d26cd56d4472e7080c15f9a06a145358d55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
